name: Empires
main: us.mcempires.empires.Empires
version: 1.0
commands:
  team:
    description: Allows the player to select a team
    usage: /team
  empiresstart:
    description: Starts the game
    usage: /empiresstart
  chat:
    description: Allows the player to toggle between team and global chat
    usage: /chat
  empiresend:
    description: Ends the game
    usage: /empiresend